import { routes } from '../../util/Constants'
const {
  DEFAULT,
  DASHBOARD_PENDINGACTION,
  DASHBOARD_UNASSIGNWORKFLOW,
  DASHBOARD_INPROGRESSTASK,
  DASHBOARD_MYGROUPPENDINGTASKS,
} = routes
export const userTaskDashboard = [
  {
    title: 'User Management',
    value: 'usermanagement',
    my: {
      pendingActions: 0,
      pendingActionURL: `${DEFAULT}${DASHBOARD_PENDINGACTION}`,
      inProgressTask: 0,
      inProgressTaskURL: `${DEFAULT}${DASHBOARD_INPROGRESSTASK}`,
    },
    myGroup: {
      pendingActions: 0,
      myGrouppendingActionURL: `${DEFAULT}${DASHBOARD_MYGROUPPENDINGTASKS}`,
      inProgressTask: 0,
      myGroupInprogressTaskURL: `${DEFAULT}${DASHBOARD_UNASSIGNWORKFLOW}`,
    },
  },
  {
    title: 'Range Change Management',
    value: 'rangechangemanagement',
    my: {
      pendingActions: 2,
      pendingActionURL: '#',
      inProgressTask: 3,
      inProgressTaskURL: '#',
    },
    myGroup: {
      pendingActions: 7,
      myGrouppendingActionURL: '#',
      inProgressTask: 15,
      myGroupInprogressTaskURL: '#',
    },
  },
  {
    title: 'Promotion & Funding',
    value: 'promotionandfunding',
    my: {
      pendingActions: 2,
      pendingActionURL: '#',
      inProgressTask: 3,
      inProgressTaskURL: '#',
    },
    myGroup: {
      pendingActions: 7,
      myGrouppendingActionURL: '#',
      inProgressTask: 15,
      myGroupInprogressTaskURL: '#',
    },
  },
  {
    title: 'Product Portal',
    value: 'productportal',
    my: {
      pendingActions: 2,
      pendingActionURL: '#',
      inProgressTask: 3,
      inProgressTaskURL: '#',
    },
    myGroup: {
      pendingActions: 0,
      myGrouppendingActionURL: '#',
      inProgressTask: 0,
      myGroupInprogressTaskURL: '#',
    },
  },
]

export const pendingStatusDetails = {
  //   userId: '40011368',
  //   status: [
  //     {
  //       details: 'myCompletedTasks',
  //       count: '0',
  //     },
  //   ],

  userId: '40114362',
  status: [
    {
      details: 'myCompletedTasks',
      count: '5',
      tasks: [
        {
          requestId: 'string',
          assignedToUserId: 'string',
          assignedToGroupId: 'string',
          assignedTimeStamp: 'string',
          taskId: 'string',
          taskName: 'string',
          requestorFullName: 'string',
          requestorRole: 'string',
          comments: 'string',
          userFirstName: 'string',
          userMiddleName: 'string',
          userLastName: 'string',
          userEmployeeId: 'string',
          userEmailId: 'string',
        },
      ],
    },
    {
      details: 'myPendingTasks',
      count: '2',
      tasks: [
        {
          requestId: '01234',
          assignedToUserId: '2345',
          assignedToGroupId: '1004',
          assignedTimeStamp: '2022-01-07',
          taskId: '01234',
          taskName: 'pending',
          requestorFullName: 'Lobo',
          requestorRole: 'role 1',
          comments: 'reassign',
          userFirstName: 'Mark',
          userMiddleName: '',
          userLastName: 'mark',
          userEmployeeId: '3456',
          userEmailId: 'mark@morrisonsplc.co.uk',
        },
        {
          requestId: '01235',
          assignedToUserId: '2346',
          assignedToGroupId: '1004',
          assignedTimeStamp: '2022-01-07',
          taskId: '01235',
          taskName: 'pending',
          requestorFullName: 'Lobo',
          requestorRole: 'role 1',
          comments: 'reassign',
          userFirstName: 'Mark',
          userMiddleName: '',
          userLastName: 'mark',
          userEmployeeId: '3456',
          userEmailId: 'mark@morrisonsplc.co.uk',
        },
      ],
    },
    {
      details: 'myInProgressTasks',
      count: '1',
      tasks: [
        {
          requestId: '01234',
          assignedToUserId: '2345',
          assignedToGroupId: '1004',
          assignedTimeStamp: '2022-01-07',
          taskId: '01234',
          taskName: 'pending',
          requestorFullName: 'Lobo',
          requestorRole: 'role 1',
          comments: 'reassign',
          userFirstName: 'Mark',
          userMiddleName: '',
          userLastName: 'mark',
          userEmployeeId: '3456',
          userEmailId: 'mark@morrisonsplc.co.uk',
        },
      ],
    },
    {
      details: 'myGroupPendingTasks',
      count: '3',
      tasks: [
        {
          requestId: '01234',
          assignedToUserId: '2345',
          assignedToGroupId: '1004',
          assignedTimeStamp: '2022-01-07',
          taskId: '01234',
          taskName: 'pending',
          requestorFullName: 'Lobo',
          requestorRole: 'role 1',
          comments: 'reassign',
          userFirstName: 'Mark',
          userMiddleName: '',
          userLastName: 'mark',
          userEmployeeId: '3456',
          userEmailId: 'mark@morrisonsplc.co.uk',
        },
        {
          requestId: '01235',
          assignedToUserId: '2345',
          assignedToGroupId: '1004',
          assignedTimeStamp: '2022-01-07',
          taskId: '01234',
          taskName: 'pending',
          requestorFullName: 'Lobo',
          requestorRole: 'role 1',
          comments: 'reassign',
          userFirstName: 'Mark',
          userMiddleName: '',
          userLastName: 'mark',
          userEmployeeId: '3456',
          userEmailId: 'mark@morrisonsplc.co.uk',
        },
        {
          requestId: '01236',
          assignedToUserId: '2345',
          assignedToGroupId: '1004',
          assignedTimeStamp: '2022-01-07',
          taskId: '01234',
          taskName: 'pending',
          requestorFullName: 'Lobo',
          requestorRole: 'role 1',
          comments: 'reassign',
          userFirstName: 'Mark',
          userMiddleName: '',
          userLastName: 'mark',
          userEmployeeId: '3456',
          userEmailId: 'mark@morrisonsplc.co.uk',
        },
      ],
    },
    {
      details: 'myGroupUnassignedWorkflows',
      count: '2',
      tasks: [
        {
          requestId: '01234',
          assignedToUserId: '2345',
          assignedToGroupId: '1004',
          assignedTimeStamp: '2022-01-07',
          taskId: '01234',
          taskName: 'pending',
          requestorFullName: 'Lobo',
          requestorRole: 'role 1',
          comments: 'reassign',
          userFirstName: 'Mark',
          userMiddleName: '',
          userLastName: 'mark',
          userEmployeeId: '3456',
          userEmailId: 'mark@morrisonsplc.co.uk',
        },
        {
          requestId: '01235',
          assignedToUserId: '2345',
          assignedToGroupId: '1004',
          assignedTimeStamp: '2022-01-07',
          taskId: '01234',
          taskName: 'pending',
          requestorFullName: 'Lobo',
          requestorRole: 'role 1',
          comments: 'reassign',
          userFirstName: 'Mark',
          userMiddleName: '',
          userLastName: 'mark',
          userEmployeeId: '3456',
          userEmailId: 'mark@morrisonsplc.co.uk',
        },
      ],
    },
  ],
}
