export const apps = [
  {
    appMenuId: 1,
    appCode: "COMDSBRD",
    appName: "Dashboard",
    menu1Code: null,
    menu1Desc: null,
    menu2Code: null,
    menu2Desc: null,
    url: "/dashboard",
    more: [],
  },
  {
    appMenuId: 2,
    appCode: "COMUSRM",
    appName: "User Management",
    menu1Code: null,
    menu1Desc: null,
    menu2Code: null,
    menu2Desc: null,
    url: "/userconfig",
    more: [],
  },
  {
    appMenuId: 3,
    appCode: "COMRANGE",
    appName: "Range Amendment",
    menu1Code: null,
    menu1Desc: null,
    menu2Code: null,
    menu2Desc: null,
    url: "/rangeamend",
    more: [],
  },
  {
    appMenuId: 4,
    appCode: "COMPROMO",
    appName: "Promotions and Funding",
    menu1Code: null,
    menu1Desc: null,
    menu2Code: null,
    menu2Desc: null,
    url: "/promofunding",
    more: [],
  },
  {
    appMenuId: 5,
    appCode: "COMPRICE",
    appName: "Retail Price Change",
    menu1Code: null,
    menu1Desc: null,
    menu2Code: null,
    menu2Desc: null,
    url: "/retailprice",
    more: [],
  },
  {
    appMenuId: 6,
    appCode: "COMSUPP",
    appName: "Supplier Portal",
    menu1Code: null,
    menu1Desc: null,
    menu2Code: null,
    menu2Desc: null,
    url: "/supplierport",
    more: [],
  },
  {
    appMenuId: 7,
    appCode: "COMPRDP",
    appName: "Product Portal",
    menu1Code: null,
    menu1Desc: null,
    menu2Code: null,
    menu2Desc: null,
    url: "/productport",
    more: [],
  },
  {
    appMenuId: 8,
    appCode: "COMUSRM",
    appName: "User Management",
    menu1Code: "CR",
    menu1Desc: "Create Request",
    menu2Code: null,
    menu2Desc: null,
    url: "/userconfig/usercreate",
    more: [],
  },
  {
    appMenuId: 9,
    appCode: "COMUSRM",
    appName: "User Management",
    menu1Code: "MU",
    menu1Desc: "Manage User",
    menu2Code: null,
    menu2Desc: null,
    url: "/userconfig/usermanage",
    more: [],
  },
  {
    appMenuId: 10,
    appCode: "COMUSRM",
    appName: "User Management",
    menu1Code: "MUG",
    menu1Desc: "Manage User Group",
    menu2Code: null,
    menu2Desc: null,
    url: "/userconfig/usergroup",
    more: [],
  },
];
