import AttachFileIcon from "@material-ui/icons/AttachFile";
export const constants = {
  viewLogRows: [
    {
      timestamp: "15-09-21 11:45",
      userID: 133456,
      role: "Role 0",
      action: "Action 0",
      attachment: <AttachFileIcon />,
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 123456,
      role: "Role 1",
      action: "Action 1",
      attachment: <AttachFileIcon />,
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 123457,
      role: "Role 2",
      action: "Action 2",
      attachment: <AttachFileIcon />,
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 123458,
      role: "Role 3",
      action: "Action 3",
      attachment: <AttachFileIcon />,
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 123459,
      role: "Role 4",
      action: "Action 4",
      attachment: <AttachFileIcon />,
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 111111,
      role: "Role 5",
      action: "Action 5",
      attachment: "",
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 111112,
      role: "Role 6",
      action: "Action 6",
      attachment: "",
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 111113,
      role: "Role 7",
      action: "Action 7",
      attachment: "",
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 111114,
      role: "Role 8",
      action: "Action 8",
      attachment: "",
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 111115,
      role: "Role 9",
      action: "Action 9",
      attachment: "",
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 111116,
      role: "Role 10",
      action: "Action 10",
      attachment: "",
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 111117,
      role: "Role 11",
      action: "Action 11",
      attachment: "",
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 111118,
      role: "Role 12",
      action: "Action 12",
      attachment: "",
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 111119,
      role: "Role 13",
      action: "Action 13",
      attachment: "",
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 111120,
      role: "Role 14",
      action: "Action 14",
      attachment: "",
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 111121,
      role: "Role 15",
      action: "Action 15",
      attachment: "",
      comments: "Some Comments",
    },
    {
      timestamp: "15-09-21 11:45",
      userID: 111122,
      role: "Role 16",
      action: "Action 16",
      attachment: "",
      comments: "Some Comments",
    },
  ],

  viewLogColumns: [
    { field: "timestamp", headerName: "Timestamp", width: 150 },
    { field: "userID", headerName: "User ID", width: 80 },
    { field: "role", headerName: "Role", width: 70 },
    { field: "action", headerName: "Action", width: 70 },
    {
      field: "attachment",
      headerName: "Attachment",
      type: "file",
      width: 80,
    },
    { field: "comments", headerName: "Comments", width: 90 },
  ],

  requestTypes: [
    {
      name: "New",
      text: "New",
    },
    {
      name: "Modify",
      text: "Modify",
    },
    {
      name: "Remove",
      text: "Remove",
    },
  ],

  statuses: [
    {
      statusID: "A",
      text: "ACTIVE",
    },
    {
      statusID: "W",
      text: "INPROGRESS",
    },
    {
      statusID: "I",
      text: "INACTIVE",
    },
    {
      statusID: "D",
      text: "DELETED",
    },
  ],
};
